Feature/redis-shopping-cart
Cheglockvvv/java pull request #8
Opened 2024-06-23 14:29 UTC by Cheglockvvv

2024-06-26 06:52 UTC, dkisliak requested changes

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/main/java/com/vorobey/userservice/cart/Cart.java
>  public class Cart implements Serializable {
implements Serializable
Why?

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/main/java/com/vorobey/userservice/controller/ShoppingCartController.java
> +        return cartOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
Не должно быть тут этой логики
Лучше кидай эксепшн и отрабатывай в excep[tion handler

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/ShoppingCartServiceImpl.java
> +        log.info("Item was added to cart successfully : {}", cartItem);
https://habr.com/ru/articles/465667/
Попробуй заюзать аннотации @Cacheable

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/ShoppingCartServiceImpl.java
> +    public Optional<Cart> getCart(Long userId) {
Optional<Cart> getCart из сервиса лучше не возвращать опшинал

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/ShoppingCartServiceImpl.java
> +            log.info("Item was not removed from cart : {} does not exist", cartKey);
Логгирование не должено быть с условием

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
А эт что*?)

2024-06-26 06:52 UTC, dkisliak commented on micro/user-service/src/test/java/com/vorobey/userservice/utils/CartModuleTests.java
> +        cart = new Cart(56L);
А в чем проблема создавать непосредственно в тесте?

2024-07-01 14:58 UTC, Cheglockvvv commented on micro/user-service/src/main/java/com/vorobey/userservice/cart/Cart.java
>  public class Cart implements Serializable {
уже убрал

2024-07-01 15:25 UTC, Cheglockvvv commented on micro/user-service/src/main/java/com/vorobey/userservice/controller/ShoppingCartController.java
> +        return cartOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
done

2024-07-01 15:25 UTC, Cheglockvvv commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/ShoppingCartServiceImpl.java
> +    public Optional<Cart> getCart(Long userId) {
done

2024-07-01 15:29 UTC, Cheglockvvv commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
изначально здесь была логика с корзиной, но потом понял, что user service нужен будет для регистрации пользователей, поэтому просто остался пустой класс

2024-07-01 15:29 UTC, Cheglockvvv commented on micro/user-service/src/test/java/com/vorobey/userservice/utils/CartModuleTests.java
> +        cart = new Cart(56L);
Никакой, решил сделать чутка красивее

2024-07-01 15:37 UTC, Cheglockvvv commented on micro/user-service/src/main/java/com/vorobey/userservice/service/impl/ShoppingCartServiceImpl.java
> +            log.info("Item was not removed from cart : {} does not exist", cartKey);
done

2024-07-03 15:00 UTC, merged